/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type UsersStatus = "ACTIVE" | "INACTIVE";

export interface Comments {
  comment: Generated<string>;
  created_at: Generated<string>;
  created_by_id: string;
  id: string;
  post_id: string;
}

export interface Posts {
  created_at: Generated<string>;
  created_by_id: string;
  details: Generated<string>;
  id: string;
  title: string;
  updated_at: Generated<string>;
}

export interface Sessions {
  created_at: Generated<string>;
  created_by_id: string;
  device: string;
  expired_at: string | null;
  id: string;
  info: Json;
  secret_hash: string;
  updated_at: Generated<string>;
}

export interface Users {
  created_at: Generated<string>;
  email: string;
  id: string;
  last_signed_in_at: string | null;
  password: string;
  status: Generated<UsersStatus>;
  updated_at: Generated<string>;
}

export interface DB {
  comments: Comments;
  posts: Posts;
  sessions: Sessions;
  users: Users;
}
