export const DOMAIN_EVENT_JOBS = {
  SEND_VERIFICATION: 'SEND_VERIFICATION',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
} as const;

export const LINE_EVENT_JOBS = {
  PROCESS_RAW: 'PROCESS_RAW',
  PROCESS_VERIFICATION: 'PROCESS_VERIFICATION',
  SHOW_SELECTION_MENU: 'SHOW_SELECTION_MENU',
  PROCESS_SELECTION_MENU: 'PROCESS_SELECTION_MENU',
  PROCESS_AI_CHAT: 'PROCESS_AI_CHAT',
} as const;

export const CRON_JOBS = {
  SAMPLE: 'SAMPLE',
} as const;
