// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'th'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * u​s​e​r​s​_​r​e​p​o​r​t​_​{​s​u​f​f​i​x​}​.​c​s​v
	 * @param {string} suffix
	 */
	usersV1Reportfilename: RequiredParams<'suffix'>
	/**
	 * I​D
	 */
	id: string
	/**
	 * E​m​a​i​l
	 */
	email: string
	/**
	 * C​r​e​a​t​e​d​ ​A​t
	 */
	createdAt: string
	/**
	 * U​p​d​a​t​e​d​ ​A​t
	 */
	updatedAt: string
	/**
	 * L​a​s​t​ ​A​c​t​i​v​e
	 */
	lastSignedInAt: string
}

export type TranslationFunctions = {
	/**
	 * users_report_{suffix}.csv
	 */
	usersV1Reportfilename: (arg: { suffix: string }) => LocalizedString
	/**
	 * ID
	 */
	id: () => LocalizedString
	/**
	 * Email
	 */
	email: () => LocalizedString
	/**
	 * Created At
	 */
	createdAt: () => LocalizedString
	/**
	 * Updated At
	 */
	updatedAt: () => LocalizedString
	/**
	 * Last Active
	 */
	lastSignedInAt: () => LocalizedString
}

export type Formatters = {}
